authentication/urls.py
from . import views
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import LoginView

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(next_page='/'), name='logout'),
    path('change-password', views.change_password, name='change_password'),
    path('reset-password', views.reset_password, name='reset_password'),
    path(
        'complete-password-reset/<uidb64>/<token>',
        views.complete_password_reset,
        name="complete_password_reset",
    ),
]

cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<str:slug>/', views.cart_add, name='cart_add'),
    path('remove/<str:slug>/', views.cart_remove, name='cart_remove'),
]

mainapp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views
from .views import (
    BaseView,
    #ProductDetailView,
    ServiceDetailView,
    #CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    #LoginView,
    #RegistrationView,
    ProfileView,
    product_detail,
    ContactsView,
    NewsView,
    AboutView,
    SertificateView,
    VacanciesView,
    PolicyView,
    DirectoryView,
    ReviewAnswerView,
    LeaveReviewView,
    TestView,
)


urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:slug>/', product_detail, name='product_detail'),
    path('service/<int:id>/', ServiceDetailView.as_view(), name='service_detail'),
    #path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    #path('login/', LoginView.as_view(), name='login'),
    #path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    #path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('news/', NewsView.as_view(), name='news'),
    path('about/', AboutView.as_view(), name='about'),
    path('sertificate/', SertificateView.as_view(), name='sertificate'),
    path('vacancies/', VacanciesView.as_view(), name='vacancies'),
    path('policy/', PolicyView.as_view(), name='policy'),
    path('directory/', DirectoryView.as_view(), name='directory'),
    path('review_answer/', ReviewAnswerView.as_view(), name='review_answer'),
    path('leave_review/', LeaveReviewView.as_view(), name='leave_review'),
    path('test/', TestView.as_view(), name='test'),

]

psprokat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('mainapp.api.urls')),
    path('authentication/', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('mainapp.urls', 'mainapp'), namespace='mainapp')),
    #path('contacts/', include(('contacts.urls', 'contacts'), namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError


class SignupForm(UserCreationForm):
    #name = models.CharField(max_length=100, verbose_name='Name')
    #age = models.IntegerField(verbose_name='Age')
    #phone = models.CharField(max_length=15, verbose_name='Number', unique=True)
    email = forms.EmailField(
        max_length=254, help_text="Required. Inform a valid email address."
    )

    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ("email",)


class SetPasswordForm(forms.Form):
    error_messages = {
        "password_mismatch": ("The two password fields didn’t match."),
    }

    new_password1 = forms.CharField(
        label=("New password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        label=("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
    )

    def clean_new_password2(self):
        password1 = self.cleaned_data.get("new_password1")
        password2 = self.cleaned_data.get("new_password2")
        if password1 and password2:
            if password1 != password2:
                raise ValidationError(
                    self.error_messages["password_mismatch"],
                    code="password_mismatch",
                )

        return password2


class SendResetEmailForm(forms.Form):
    email = forms.EmailField(
        max_length=254, help_text="Required. Inform a valid email address."
    )

authentication/forms.py
from django import forms
from django.contrib.auth.models import User


class LoginForm(forms.ModelForm):
    """"""
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Пользователь с логином {username} не найден в системе.')
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("Неверный пароль")
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password']

authentication/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login, update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.core.validators import validate_email
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_str
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.urls import reverse
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.core.exceptions import ValidationError
import logging
from .email_thread import EmailThread
from .models import SetPasswordForm, SendResetEmailForm, SignupForm
from django.http import HttpResponseRedirect
from django.views.generic import View
from .forms import LoginForm
from django.contrib.auth import authenticate, login

logger = logging.getLogger(__name__)


class LoginView(View):
    """"""
    def get(self, request, *args, **kwargs):
        form = LoginForm(request.POST or None)
        context = {'form': form}
        return render(request, 'registration/login.html', context)

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect('/')
        context = {'form': form}
        return render(request, 'registration/login.html', context)


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            logger.info("Logging was a success")
            return HttpResponseRedirect('/')
        else:
            logger.warning(f"Signup was not valid")
            messages.error(request, "Signup is not valid")

    form = SignupForm()
    context = dict(form=form)
    return render(request, 'authentication/signup.html', context)


def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Your password was successfully updated!")
            logger.info("Password for was changed")
            return HttpResponseRedirect('/')
        else:
            logger.warning("Password change was not vaid")
            messages.error(request, "change password is not valid")

    form = PasswordChangeForm(request.user)
    return render(request, "authentication/change_password.html", dict(form=form))


def reset_password(request):
    context = dict(form=SendResetEmailForm())

    if request.method == "POST":
        form = SendResetEmailForm(request.POST)

        if not form.is_valid():
            logger.warning("Invalid email")
            messages.error(request, "Please, use valid email")
            return render(request, "authentication/reset_password.html", context)

        email = form.cleaned_data["email"]

        try:
            validate_email(email)
        except ValidationError:
            logger.warning("Invalid email")
            messages.error(request, "Please, use valid email")
            return render(request, 'authentication/reset_password.html', context)

        current_site = get_current_site(request)

        user = User.objects.filter(email=email)

        if not user.exists():
            messages.error(request, "No users registered with this email")
            logger.warning(f"There was no user for {email}")
            return render(request, 'authentication/reset_password.html', context)

        email_content = {
            "user": user[0],
            "domain": current_site.domain,
            "uid": urlsafe_base64_encode(force_bytes(user[0].pk)),
            "token": PasswordResetTokenGenerator().make_token(user[0]),
        }

        link = reverse(
            'authentication:complete_password_reset',
            kwargs=dict(uidb64=email_content["uid"], token=email_content["token"]),
        )

        email_subject = "Password reset instructions"

        reset_url = f"http://{current_site.domain}{link}"

        email = EmailMessage(
            email_subject,
            f"Hi {user[0].username}, Please open the link below to reset your password \n{reset_url}",
            "noreply@semycolon.com",
            [email],
        )

        EmailThread(email).start()

        logger.info(f"Email was sent to {email}")
        messages.success(request, "We send you an email with reset")

    return render(request, "authentication/reset_password.html", context)


def complete_password_reset(request, uidb64, token):
    try:
        user_id = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(id=user_id)

        if not PasswordResetTokenGenerator().check_token(user, token):
            messages.info(request, "This link is invalid, request a new link")
            return redirect("index")
    except:
        logger.warning("Attempt of use of old link")
        messages.error(request, "Something went wrong, request another link")
        return redirect("index")

    if request.method == "POST":
        form = SetPasswordForm(request.POST)
        if not form.is_valid():
            logger.warning("Password change was invalid")
            messages.error(request, "Passwords do not match")
        else:
            user.set_password(form.cleaned_data["new_password1"])
            user.save()
            logger.info("Password reset via email successful")
            messages.success(request, "Password reset successful")
            return redirect('authentication:login')

    form = SetPasswordForm()
    context = dict(uidb64=uidb64, token=token, form=form)

    return render(request, "authentication/set_new_password.html", context)



authentication/templates/authentication/base.html
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/all.js"></script>
    <link href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <title>ISTORE</title>
  </head>
  <body>

{% load static %}
<nav class="navbar navbar-expand-md navbar-dark sticky-top bg-dark " data-sidebarClass="navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'mainapp:base' %}" style="margin-left: 15px">
        ISTORE
    </a>
    {% if request.user.is_authenticated %}
    <ul class="nav navbar-nav ms-auto" style="margin-right: 15px">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown">
                Welcome, {{ request.user.username }}
            </a>
            <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'authentication:logout' %}">Logout</a>
            <a class="dropdown-item" href="{% url 'authentication:change_password' %}">Change Password</a>
            </div>
        </li>
    </ul>
    {% else %}
    <ul class="navbar-nav ms-auto" style="margin-right: 15px">
        <li class="nav-item {% if request.resolver_match.url_name == 'login' %} active {% endif %}">
            <a class="nav-link" href="{% url 'authentication:login' %}">Login</a>
        </li>
        <li class="nav-item {% if request.resolver_match.url_name == 'signup' %} active {% endif %}">
            <a class="nav-link" href="{% url 'authentication:signup' %}">Sign Up</a>
        </li>
    </ul>
    {% endif %}
</nav>
    <div class="container">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

authentication/templates/authentication/change_password.html
{% extends 'authentication/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    {% include 'authentication/message_list.html' %}
    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <div class="col-lg-6 col-md-6 offset-lg-3 offset-md-3 col-sm-12 col-xs-12 alert alert-danger">{{ error }}</div>
        {% endfor %}
    {% endif %}
    <div class="row">
        <div class="col-lg-6 col-md-6 offset-md-3">
            <h1>Login</h1>
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-6 offset-md-3">
            <form method="POST" class="post-form">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Sign in</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

authentication/templates/authentication/message_list.html
{% for message in messages %}
<div class="alert alert-success">
    <a class="close" href="#" data-dismiss="alert">×</a>
    {{ message }}
</div>
{% endfor %}

authentication/templates/authentication/reset_password.html
{% extends 'authentication/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="col-lg-6 col-md-6 offset-md-3">
            <h1>Enter your email</h1>
            <hr>

            {% include 'authentication/message_list.html' %}

            <form method="POST" class="post-form">
                {% csrf_token %}
                    <div class="row">
                        {% for field in form %}
                        <div class="form-group col-lg-6 col-md-6">
                            {{ field | as_crispy_field }}
                        </div>
                        {% endfor %}
                    </div>
                <button type="submit" class="btn btn-primary">Send</button>
            </form>
        </div>
    </div>


{% endblock %}

authentication/templates/authentication/set_new_password.html

{% extends 'authentication/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="col-lg-6 col-md-6 offset-md-3">
            <h1>Set new password</h1>
            <hr>

            {% include 'authentication/message_list.html' %}

            <form method="POST" class="post-form">
                {% csrf_token %}
                    <div class="row">
                        {% for field in form %}
                        <div class="form-group col-lg-6 col-md-6">
                            {{ field | as_crispy_field }}
                        </div>
                        {% endfor %}
                    </div>
                <button type="submit" class="btn btn-primary">Sign in</button>
            </form>
        </div>
    </div>


{% endblock %}

authentication/templates/authentication/signup.html
{% extends 'authentication/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="col-lg-6 col-md-6 offset-md-3">
            <h1>Sign up</h1>
            <hr>

            {% include 'authentication/message_list.html' %}

            <form method="POST" class="post-form">
                {% csrf_token %}
                    <div class="row">
                        {% for field in form %}
                        <div class="form-group col-lg-6 col-md-6">
                            {{ field | as_crispy_field }}
                        </div>
                        {% endfor %}
                    </div>
                <button type="submit" class="btn btn-primary">Sign in</button>
            </form>
        </div>
    </div>


{% endblock %}