cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<str:slug>/', views.cart_add, name='cart_add'),
    path('remove/<str:slug>/', views.cart_remove, name='cart_remove'),
]

mainapp/api/urls.py
from django.urls import path

from .api_views import (
    ProductAPIView,
    ProductDetailAPIView
)


urlpatterns = [
    path('products/', ProductAPIView.as_view(), name='products_list'),
    path('products/<str:id>/', ProductDetailAPIView.as_view(), name='products_detail')
]

mainapp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views
from .views import (
    BaseView,
    #ProductDetailView,
    ServiceDetailView,
    #CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    #LoginView,
    #RegistrationView,
    ProfileView,
    product_detail,
    ContactsView,
    NewsView,
    AboutView,
    SertificateView,
    VacanciesView,
    PolicyView,
    DirectoryView,
    ReviewAnswerView,
    LeaveReviewView,
    TestView,
)


urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:slug>/', product_detail, name='product_detail'),
    path('service/<int:id>/', ServiceDetailView.as_view(), name='service_detail'),
    #path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    #path('login/', LoginView.as_view(), name='login'),
    #path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    #path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('news/', NewsView.as_view(), name='news'),
    path('about/', AboutView.as_view(), name='about'),
    path('sertificate/', SertificateView.as_view(), name='sertificate'),
    path('vacancies/', VacanciesView.as_view(), name='vacancies'),
    path('policy/', PolicyView.as_view(), name='policy'),
    path('directory/', DirectoryView.as_view(), name='directory'),
    path('review_answer/', ReviewAnswerView.as_view(), name='review_answer'),
    path('leave_review/', LeaveReviewView.as_view(), name='leave_review'),
    path('test/', TestView.as_view(), name='test'),

]

psprokat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('mainapp.api.urls')),
    path('authentication/', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('mainapp.urls', 'mainapp'), namespace='mainapp')),
    #path('contacts/', include(('contacts.urls', 'contacts'), namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Order
from .models import Review


class OrderForm(forms.ModelForm):
    """"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = 'Дата получения заказа'

    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'buying_type', 'order_date', 'comment'
        )


class LoginForm(forms.ModelForm):
    """"""
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Пользователь с логином {username} не найден в системе.')
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("Неверный пароль")
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password']


class RegistrationForm(forms.ModelForm):

    confirm_password = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)
    phone = forms.CharField(required=False)
    address = forms.CharField(required=False)
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'
        self.fields['confirm_password'].label = 'Подтвердите пароль'
        self.fields['phone'].label = 'Номер телефона'
        self.fields['first_name'].label = 'Ваше имя'
        self.fields['last_name'].label = 'Ваша фамилия'
        self.fields['address'].label = 'Адрес'
        self.fields['email'].label = 'Электронная почта'

    def clean_email(self):
        email = self.cleaned_data['email']
        domain = email.split('.')[-1]
        if domain in ['com', 'net']:
            raise forms.ValidationError(f'Регистрация для домена "{domain}" невозможна')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(f'Данный почтовый адрес уже зарегистрирован в системе')
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Имя {username} занято')
        return username

    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('Пароли не совпадают')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password', 'first_name', 'last_name', 'address', 'phone', 'email']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['name', 'email', 'message', 'rating']

    message = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите текст отзыва'}))

mainapp/views.py
from django.db import transaction
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView, TemplateView
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from .models import Service, Order, Customer, Product  # CartProduct
# from .mixins import CartMixin
from .forms import OrderForm, LoginForm, RegistrationForm
from .utils import recalc_cart
from importlib import import_module
from cart.forms import CartAddProductForm

from django.conf import settings
from django.http import JsonResponse
from django.views.generic import View
from .models import Review
from .forms import ReviewForm
from django.shortcuts import render, redirect


class BaseView(View):  # CartMixin
    """"""

    def get(self, request, *args, **kwargs):
        services = Service.objects.all()
        products = Product.objects.all()
        context = {
            'services': services,
            'products': products,
            # 'cart': self.cart
        }
        return render(request, 'mainapp/base.html', context)


# class ProductDetailView(DetailView):  #CartMixin
#    """"""
#    context_object_name = 'product'
#    template_name = 'product_detail.html'
#    slug_url_kwarg = 'slug'
#
#    def get_context_data(self, **kwargs):
#        context = super().get_context_data(**kwargs)
#        context['cart'] = self.cart
#        return context


class ServiceDetailView(DetailView):  # CartMixin
    """"""
    model = Service
    queryset = Service.objects.all()
    context_object_name = 'service'
    template_name = 'service_detail.html'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = self.cart
        return context


class AddToCartView(View):  # CartMixin
    """"""

    def get(self, request, *args, **kwargs):
        product_slug = kwargs.get('slug')
        product = Product.objects.get(slug=product_slug)
        # cart_product, created = CartProduct.objects.get_or_create(
        #    user=self.cart.owner, cart=self.cart, product=product
        # )
        # if created:
        #    self.cart.products.add(cart_product)
        # recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, "Товар успешно добавлен")
        return HttpResponseRedirect('/cart/')


class DeleteFromCartView(View):
    """"""

    def get(self, request, *args, **kwargs):
        product_slug = kwargs.get('slug')
        product = Product.objects.get(slug=product_slug)
        # cart_product = CartProduct.objects.get(
        #    user=self.cart.owner, cart=self.cart, product=product,
        # )
        # self.cart.products.remove(cart_product)
        # cart_product.delete()
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, "Товар успешно удален")
        return HttpResponseRedirect('/cart/')


class ChangeQTYView(View):
    """"""

    def post(self, request, *args, **kwargs):
        product_slug = kwargs.get('slug')
        product = Product.objects.get(slug=product_slug)
        qty = int(request.POST.get('qty'))
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, "Кол-во товара успешно изменено")
        return HttpResponseRedirect('/cart/')


class CheckoutView(View):
    """"""

    def get(self, request, *args, **kwargs):
        services = Service.objects.all()
        form = OrderForm(request.POST or None)
        context = {
            # 'cart': self.cart,
            'services': services,
            'form': form
        }
        return render(request, 'checkout.html', context)


class MakeOrderView(View):
    """"""

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        form = OrderForm(request.POST or None)
        customer = Customer.objects.get(user=request.user)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.customer = customer
            new_order.first_name = form.cleaned_data['first_name']
            new_order.last_name = form.cleaned_data['last_name']
            new_order.phone = form.cleaned_data['phone']
            new_order.address = form.cleaned_data['address']
            new_order.buying_type = form.cleaned_data['buying_type']
            new_order.order_date = form.cleaned_data['order_date']
            new_order.comment = form.cleaned_data['comment']
            new_order.save()
            self.cart.in_order = True
            self.cart.save()
            new_order.cart = self.cart
            new_order.save()
            customer.orders.add(new_order)
            messages.add_message(request, messages.INFO, 'Спасибо за заказ! Менеждер с Вами свяжется')
            return HttpResponseRedirect('/')
        return HttpResponseRedirect('/checkout/')


class ProfileView(View):

    def get(self, request, *args, **kwargs):
        customer = Customer.objects.get(user=request.user)
        orders = Order.objects.filter(customer=customer).order_by('-created_at')
        services = Service.objects.all()
        return render(
            request,
            'profile.html',
            {'orders': orders, 'cart': self.cart, 'services': services}
        )


class ContactsView(TemplateView):
    template_name = 'contact.html'


class NewsView(TemplateView):
    template_name = 'news.html'


class AboutView(TemplateView):
    template_name = 'about.html'


class SertificateView(TemplateView):
    template_name = 'certificates.html'


class VacanciesView(TemplateView):
    template_name = 'vacancy.html'


class PolicyView(TemplateView):
    template_name = 'policy.html'


class ReviewAnswerView(TemplateView):
    template_name = 'review_answer.html'


class LeaveReviewView(View):
    template_name = 'leave_review.html'

    def get(self, request, *args, **kwargs):
        form = ReviewForm()
        return render(request, self.template_name, {'form': form, 'review_submitted': False})

    def post(self, request, *args, **kwargs):
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            print("Form saved successfully!")  # Добавьте этот принт
            return redirect('mainapp:review_answer')  # Перенаправление после успешного сохранения
        print("Form is not valid!")  # Добавьте этот принт
        return render(request, self.template_name, {'form': form})


class TestView(TemplateView):
    template_name = 'test.html'


class DirectoryView(TemplateView):
    template_name = 'directory.html'


def product_detail(request, slug):
    product = get_object_or_404(Product,
                                # id=id,
                                slug=slug,
                                # available=True
                                )
    cart_product_form = CartAddProductForm()
    return render(request, 'mainapp/product_detail.html', {'product': product, 'cart_product_form': cart_product_form})

mainapp/templates/about.html
{% extends 'mainapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
      rel="stylesheet"
    />
    <title>О компании</title>
  </head>
  <body>
    <section class="">
      <div class="container">
          <h2 class="about-section-title">О магазине:</h2>
          <h2>
            i-Store (айСтор) – официальный партнёр компании Apple в Беларуси.
          </h2>

          <dl>
            <dt>i-Store</dt>
            <dd>Официальный партнёр компании Apple в Беларуси</dd>
          </dl>

          <p>
            В наших магазинах можно не только купить iPhone, компьютер Mac или
            планшет iPad, а также другую технику Apple и аксессуары для неё.
            i-Store – это прежде всего место, пропитанное атмосферой Apple, в
            котором вам помогут с выбором техники, научат ей пользоваться, дадут
            советы по эксплуатации ваших гаджетов и предложат качественные
            аксессуары.
          </p>
          <p>
            В i-Store можно поработать с любым Mac, iPhone или с iPad,
            посмотреть демонстрации недавно появившихся в продаже продуктов
            Apple или принять участие в тренингах, мастер-классах и
            мероприятиях, посвящённых новейшим технологиям. Просто спросите, и
            мы подберем подходящий курс для вас. Мы знаем о продуктах Apple всё.
            И мы готовы поделиться знаниями.
          </p>
          <p>
            Наши продавцы — настоящие эксперты в своей области. А качественная,
            удобная, простая в использовании техника Apple доставляет
            удовольствие своим пользователям и практически не требует
            технической поддержки
          </p>
          <p>Наши магазины:</p>
          <p>
            <strong>Ленина, 5</strong> |
            <a href="tel:+375445555892" style="color: black"
              >+375 (44) 555-58-92</a
            ><br />Пн – Вс: 09:00 – 21:00<br />Для посетителей магазина работает
            бесплатная парковка. Чтобы ей воспользоваться - позвоните, вам
            откроют въезд.
          </p>
          <p>
            <strong>Galleria Minsk</strong> пр-т Победителей, 9 |
            <a href="+375293867804" style="color: black">+375 (29) 386-78-04</a>
            <br /> <time datetime="10:00+4:0">Пн – Вс: 10:00</time>
            <time datetime="22:00+4:0">- 22:00</time>
          </p>
          <p>
            В нашем магазине вы всегда купите все, что вам нужно.
          </p>
        </div>
            <div class="benefit-container">
              <div class="benefit-item">
                <img
                  src="https://cdn0.it4profit.com/files/15/benefit-1.svg"
                  alt="benefit-1-icon"
                  class="img_benefit"
                />
                <p class="benefit-title">Первичная настройка.</p>
                <p class="benefit-description">
                  Мы объясним, как подготовить ваше новое устройство к работе.
                  Поможем активировать его, выбрать язык, настроить защиту. А
                  также подключить девайс к сервисам Apple – это делается сразу
                  после первого включения.Пример текста в виде четверостишия с фиксированным и потенциальным переводом строки
                </p>
              </div>
              <div class="benefit-item">
                <img
                  src="https://cdn0.it4profit.com/files/15/benefit-2.svg"
                  alt="benefit-2-icon"
                  class="img_benefit"
                />
                <p class="benefit-title">Большой выбор аксессуаров</p>
                <p class="benefit-description">
                  для защиты ваших устройств: чехлы, защитные стекла, обложки,
                  сумки. А также периферийные устройства, которые идеально
                  совместимы с техникой Apple: стилусы, клавиатуры, мыши,
                  наушники, акустика, и многое другое.
                </p>
              </div>
              <div class="benefit-item">
                <img
                  src="https://cdn0.it4profit.com/files/15/benefit-3.svg"
                  alt="benefit-3-icon"
                  class="img_benefit"
                />
                <p class="benefit-title">Сервисное обслуживание.</p>
                <p class="benefit-description">
                  Наши специалисты помогут подготовить ваш новый девайс к работе
                  еще до выхода из магазина. Наклеят защитное стекло, подберут
                  аксессуары. При необходимости – установят программы и
                  перенесут данные.
                </p>
              </div>
              <div class="benefit-item">
                <img
                  src="https://cdn0.it4profit.com/files/15/benefit-4.svg"
                  alt="benefit-4-icon"
                  class="img_benefit"
                />
                <p class="benefit-title">Персональное обучение.</p>
                <p class="benefit-description">
                  Это индивидуальный тренинг, на котором вы с нуля научитесь
                  пользоваться вашим новым гаджетом. Наш сотрудник расскажет,
                  какие приложения будут вам полезны. И покажет, какие
                  возможности открывает экосистема Apple.
                </p>
              </div>
              <div class="benefit-item">
                <img
                  src="https://cdn0.it4profit.com/files/15/benefit-5.svg"
                  alt="benefit-5-icon"
                  class="img_benefit"
                />
                <p class="benefit-title">Trade-in.</p>
                <p class="benefit-description">
                  Это система, по которой мы возьмем в зачет ваши старые
                  устройства Apple при покупке новой техники. Сдаете несколько
                  девайсов? Их стоимость суммируется, а оставшуюся часть вы
                  можете доплатить сразу или оформить в рассрочку, кредит.
                </p>
              </div>
              <div class="benefit-item">
                <img
                  src="https://cdn0.it4profit.com/files/15/benefit-6.svg"
                  alt="benefit-6-icon"
                  class="img_benefit"
                />
                <p class="benefit-title">Удобные варианты оплаты.</p>
                <p class="benefit-description">
                  У нас вы можете купить технику по карте или за наличные
                  деньги. А также оформить рассрочку или кредит на срок от 2 до
                  48 месяцев. Мы принимаем карты «Халва», «Черепаха», «КартаFun»
                  и «Карта покупок».
                </p>
              </div>
              <div class="benefit-item">
                <img
                  src="https://cdn0.it4profit.com/files/15/benefit-7.svg"
                  alt="benefit-7-icon"
                  class="img_benefit"
                />
                <p class="benefit-title">Доставка по всей стране.</p>
                <p class="benefit-description">
                  Мы доставим новое устройство вам или вашим близким, где бы вы
                  ни находились. Долго ждать не придется: отправка
                  осуществляется на следующий день после оплаты. Ее стоимость
                  формируется автоматически в момент оформления заказа.
                </p>
              </div>
            </div>
    </section>
  </body>
</html>
{% endblock content %}

mainapp/templates/directory.html
{% extends 'mainapp/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
      rel="stylesheet"
    />
    <title>Справочник</title>
</head>
<body>
    <section class="faq">
      <details>
        <summary id="test1">Могу ли я оформить рассрочку?</summary>
        <p>На данный момент банки-партнёры не предоставляют рассрочек,
            однако вы можете оформить кредит, посетив любой магазин сети
            <span>The iStore для более подробной информации об условиях банка.</span></p>
      </details>
      <details>
        <summary id="start">Куда обращаться в случае если устройство не работает?</summary>
        <p>По вопросам гарантийного и постгарантийного обслуживания оборудования можно
            обратиться: в любой магазин сети The iStore, позвонить на
            горячую линию 8 029 524 58 45 или по телефону +375 29 154 58 45</p>
      </details>
      <details>
        <summary id="test">Возможен ли самовывоз заказанного товара?</summary>
        <p id="testside">У Вас есть возможность самостоятельно забрать оплаченные товары.
            Минимальная сумма заказа отсутствует. <span>Платить за самовывоз не нужно.</span></p>
      </details>
      <details>
        <summary id="start1">Возможна ли доставка в города где нет ваших магазинов?</summary>
        <p>Да, вы можете приобрести товары у нас, даже если проживаете в другом регионе.
            <span>Доставка в города где нет наших магазинов сети The iStore, а сумма покупки менее 500р,
                осуществляется транспортной компанией и только при 100% предоплате.</span> Стоимость доставки составит
            20р для малогабаритного товара и 40р для крупногабаритного товара.</p>
      </details>
        <details>
        <summary id="insideme">Какие сроки доставки?</summary>
        <p>Доставка осуществляется компанией СДЭК, обычно в течении 5-7 дней</p>
      </details>
    </section>
</body>
</html>
{% endblock content %}

mainapp/templates/leave_review.html
{% extends 'mainapp/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
      rel="stylesheet"
    />
    <title>Отзывы</title>
</head>
<body>
    <div class="customer">
        <div class="wrapper">
            <h2>Отзывы</h2>
            <div class="customer_content">
                <div class="customer_item">
                    <div class="customer_star">
                        <img src="/media/starr.png" alt="st" class="star">
                        <img src="/media/starr.png" alt="st" class="star">
                        <img src="/media/starr.png" alt="st" class="star">
                        <img src="/media/starr.png" alt="st" class="star">
                        <img src="/media/starr.png" alt="st" class="star">
                    </div>
                    <div class="customer_subtitle">
                        <p>
                            Отличный магазин и отличный сервис. И лучший консультант который мне встречался .
                            Его имя Максим. Огромное спасибо за то что уделил время и все рассказал .
                            Удачи и процветания магазину и Максиму
                        </p>
                    </div>
                    <div class="customer_footer">
                        <img src="/media/menn.png" alt="men" class="img_footer">
                        <div class="customer_footer_text">
                            <div class="customer_name"><p>Артемий</p></div>
                            <div class="customer_surname"><p>Покупатель</p></div>
                        </div>
                    </div>
                </div>
                <div class="customer_item">
                    <div class="customer_star">
                        <img src="/media/starr.png" alt="st" class="star">
                        <img src="/media/starr.png" alt="st" class="star">
                        <img src="/media/starr.png" alt="st" class="star">
                        <img src="/media/starr.png" alt="st" class="star">
                        <img src="/media/starr.png" alt="st" class="star">
                    </div>
                    <div class="customer_subtitle">
                        <p>
                            Персонал отличный всегда подскажет что выбрать.
                            Цены на iPhone лучшие в Минске. Качество отличное. Скидок много.10/10
                        </p>
                    </div>
                    <div class="customer_footer">
                        <img src="/media/menn.png" alt="men" class="img_footer">
                        <div class="customer_footer_text">
                            <div class="customer_name"><p>Максим</p></div>
                            <div class="customer_surname"><p>Покупатель</p></div>
                        </div>
                    </div>
                </div>
                <div class="customer_item">
                    <div class="customer_star">
                        <img src="/media/starr.png" alt="st" class="star">
                        <img src="/media/starr.png" alt="st" class="star">
                        <img src="/media/starr.png" alt="st" class="star">
                        <img src="/media/starr.png" alt="st" class="star">
                        <img src="/media/starr.png" alt="st" class="star">
                    </div>
                    <div class="customer_subtitle">
                        <p>
                            Внимательный персонал, помогают по всем вопросам.
                            Особенно благодарю консультанта Данила, помог разобраться с новыми наушниками!
                        </p>
                    </div>
                    <div class="customer_footer">
                        <img src="/media/menn.png" alt="men" class="img_footer">
                        <div class="customer_footer_text">
                            <div class="customer_name"><p>Александр</p></div>
                            <div class="customer_surname"><p>Покупатель</p></div>
                        </div>
                    </div>
                </div>
            </div>
                    <details class="details_form">
                <summary  class="summary_form">Добавить отзыв</summary>
                {% if review_submitted %}
                <p>Ваш отзыв успешно отправлен. Спасибо!</p>
                <a href="{% url 'mainapp:review_answer' %}">Вернуться к отзывам</a>
            {% else %}
                <form class="form_review" method="post" action="{% url 'mainapp:leave_review' %}">
                    {% csrf_token %}
                    <label for="{{ form.name.id_for_label }}">Ваше имя:</label>
                    <input type="text" id="{{ form.name.id_for_label }}" name="{{ form.name.name }}" placeholder="Введите ваше имя" >

                    <label for="{{ form.email.id_for_label }}">Ваш Email:</label>
                    <input type="text" id="{{ form.email.id_for_label }}" name="{{ form.email.name }}" placeholder="Введите ваш Email" >

                    <label for="{{ form.message.id_for_label }}">Текст отзыва:</label>
                    <input type="text" id="{{ form.message.id_for_label }}" name="{{ form.message.name }}" placeholder="Введите текст отзыва" >

                    <label for="{{ form.rating.id_for_label }}">Оценка:</label>
                    <select id="{{ form.rating.id_for_label }}" name="{{ form.rating.name }}">
                        {% for value, text in form.rating.field.choices %}
                            <option value="{{ value }}" {% if form.rating.value == value %}selected{% endif %}>{{ text }}</option>
                        {% endfor %}
                    </select>

                    <button type="submit">Отправить</button>
                </form>
            {% endif %}
            </details>

        </div>
    </div>
</body>
</html>
{% endblock content %}

mainapp/templates/review_answer.html
{% extends "mainapp/base.html" %}

{% block title %}Thank you{% endblock %}

{% block content %}
       {% if review_submitted %}
        <p>Ваш отзыв успешно отправлен. Спасибо!</p>
        <a href="{% url 'review_answer' %}">Вернуться к отзывам</a>
    {% else %}
        <h1>Спасибо!</h1>
        <p class="review_answer">Ваш отзыв успешно отправлен!</p>
    {% endif %}
{% endblock %}