cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<str:slug>/', views.cart_add, name='cart_add'),
    path('remove/<str:slug>/', views.cart_remove, name='cart_remove'),
]

mainapp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views
from .views import (
    BaseView,
    #ProductDetailView,
    ServiceDetailView,
    #CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    #LoginView,
    #RegistrationView,
    ProfileView,
    product_detail,
    ContactsView,
    NewsView,
    AboutView,
    SertificateView,
    VacanciesView,
    PolicyView,
    DirectoryView,
    ReviewAnswerView,
    LeaveReviewView,
    TestView,
)


urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:slug>/', product_detail, name='product_detail'),
    path('service/<int:id>/', ServiceDetailView.as_view(), name='service_detail'),
    #path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    #path('login/', LoginView.as_view(), name='login'),
    #path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    #path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('news/', NewsView.as_view(), name='news'),
    path('about/', AboutView.as_view(), name='about'),
    path('sertificate/', SertificateView.as_view(), name='sertificate'),
    path('vacancies/', VacanciesView.as_view(), name='vacancies'),
    path('policy/', PolicyView.as_view(), name='policy'),
    path('directory/', DirectoryView.as_view(), name='directory'),
    path('review_answer/', ReviewAnswerView.as_view(), name='review_answer'),
    path('leave_review/', LeaveReviewView.as_view(), name='leave_review'),
    path('test/', TestView.as_view(), name='test'),

]

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

psprokat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('mainapp.api.urls')),
    path('authentication/', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('mainapp.urls', 'mainapp'), namespace='mainapp')),
    #path('contacts/', include(('contacts.urls', 'contacts'), namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from mainapp.models import Product
from django.contrib import messages
from .cart import Cart
from .forms import CartAddProductForm
from django.http import HttpResponseRedirect
from django.http import HttpResponseRedirect


@require_POST
def cart_add(request, slug):
    if request.user.is_authenticated:
        cart = Cart(request)
        product = get_object_or_404(Product, slug=slug)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product,
                     quantity=cd['quantity'],
                     update_quantity=cd['update'])
    else:
        return redirect('authentication:login')
    return redirect('cart:cart_detail')


def cart_remove(request, slug):
    cart = Cart(request)
    product = Product.objects.get(slug=slug)
    cart.remove(product)
    messages.add_message(request, messages.INFO, "Товар успешно удален")
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <h3 class="text-center mt-5 mb-5">Ваша корзина{% if not cart %} пуста {% endif %}</h3>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
    {% endif %}
{% if cart %}
    <table class="table">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Товар</th>
            <th>Количество</th>
            <th>Цена</th>
            <th>Итого</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <img src="{{ product.image.url }}" width="400" height="400" hspace="10">
                    </td>
                    <td>{{ product.title }}
                        <a href="{% url 'cart:cart_remove' product.slug%}">Удалить</a>
                    </td>
                    <td>{{ item.quantity }}</td>
                    <td class="num">{{ item.price }}BYN</td>
                    <td class="num">{{ item.total_price }}BYN</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }}BYN</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'mainapp:base' %}" class="button light">Продолжть покупки</a>
        <a href="{% url 'orders:order_create' %}" class="button">
            Оформить заказ
        </a>
    </p>
{% endif %}
{% endblock %}