authentication/urls.py
from . import views
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import LoginView

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(next_page='/'), name='logout'),
    path('change-password', views.change_password, name='change_password'),
    path('reset-password', views.reset_password, name='reset_password'),
    path(
        'complete-password-reset/<uidb64>/<token>',
        views.complete_password_reset,
        name="complete_password_reset",
    ),
]

cart/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<str:slug>/', views.cart_add, name='cart_add'),
    path('remove/<str:slug>/', views.cart_remove, name='cart_remove'),
]

mainapp/api/urls.py
from django.urls import path

from .api_views import (
    ProductAPIView,
    ProductDetailAPIView
)


urlpatterns = [
    path('products/', ProductAPIView.as_view(), name='products_list'),
    path('products/<str:id>/', ProductDetailAPIView.as_view(), name='products_detail')
]

mainapp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views
from .views import (
    BaseView,
    #ProductDetailView,
    ServiceDetailView,
    #CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    #LoginView,
    #RegistrationView,
    ProfileView,
    product_detail,
    ContactsView,
    NewsView,
    AboutView,
    SertificateView,
    VacanciesView,
    PolicyView,
    DirectoryView,
    ReviewAnswerView,
    LeaveReviewView,
    TestView,
)


urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:slug>/', product_detail, name='product_detail'),
    path('service/<int:id>/', ServiceDetailView.as_view(), name='service_detail'),
    #path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    #path('login/', LoginView.as_view(), name='login'),
    #path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    #path('registration/', RegistrationView.as_view(), name='registration'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('news/', NewsView.as_view(), name='news'),
    path('about/', AboutView.as_view(), name='about'),
    path('sertificate/', SertificateView.as_view(), name='sertificate'),
    path('vacancies/', VacanciesView.as_view(), name='vacancies'),
    path('policy/', PolicyView.as_view(), name='policy'),
    path('directory/', DirectoryView.as_view(), name='directory'),
    path('review_answer/', ReviewAnswerView.as_view(), name='review_answer'),
    path('leave_review/', LeaveReviewView.as_view(), name='leave_review'),
    path('test/', TestView.as_view(), name='test'),

]

psprokat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('mainapp.api.urls')),
    path('authentication/', include(('authentication.urls', 'authentication'), namespace='authentication')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('mainapp.urls', 'mainapp'), namespace='mainapp')),
    #path('contacts/', include(('contacts.urls', 'contacts'), namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.utils import timezone

User = get_user_model()


class Service(models.Model):
    """"""
    name = models.CharField(max_length=255, verbose_name='Имя услуги')
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('mainapp:service_detail', args=[self.id])


class Product(models.Model):
    """"""
    service = models.ForeignKey(Service, verbose_name='Услуга', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return self.title

    def get_model_name(self):
        return self.__class__.__name__.lower()

    def get_absolute_url(self):
        return reverse('mainapp:product_detail', args=[self.slug])

    def get_fields_for_filter_in_template(self):
        return ProductFeatures.objects.filter(
            service=self,
            use_in_filter=True,
        ).perfetch_related('service').value('feature_key', 'feature_measure', 'feature_name')


class ProductFeatures(models.Model):
    RADIO = 'radio'
    CHECKBOX = 'checkbox'

    FILTER_TYPE_CHOICES = (
        (RADIO, 'Радиокнопка'),
        (CHECKBOX, 'Чекбокс')
    )
    feature_key = models.CharField(max_length=100, verbose_name='Ключ харакетристик')
    feature_name = models.CharField(max_length=255, verbose_name='Наименование характеристики')
    service = models.ForeignKey(Service, verbose_name='Услуга', on_delete=models.CASCADE)
    postfix_for_value = models.CharField(
        max_length=20,
        null=True,
        blank=True,
        verbose_name='Постфикс для значения',
        help_text=f'Например для характеристики "Часы работы" к '
                  f'значению можно добавить постфикс "часов", и как результат - значение "10 часов"'
    )
    use_in_filter = models.BooleanField(
        default=False,
        verbose_name='Использовать в фильтрации товаров в шаблоне',
    )
    filter_type = models.CharField(
        max_length=20,
        verbose_name='Тип фильтра',
        default=CHECKBOX,
        choices=FILTER_TYPE_CHOICES
    )
    filter_measure = models.CharField(
        max_length=50,
        verbose_name='Единица измерения для фильтров',
        help_text='Единица измерения для конкретного фильтра. Например "Частота процессора (Ghz)."'
                  'Единицей измерения будет информация в скобках.'
    )

    def __str__(self):
        return f'Услуга - "{self.service.name}" | Характеристика - "{self.feature_name}"'


class ProductFeatureValidators(models.Model):
    service = models.ForeignKey(Service, verbose_name='Услуга', on_delete=models.CASCADE)
    feature = models.ForeignKey(
        ProductFeatures, verbose_name='Характеристика', null=True, blank=True, on_delete=models.CASCADE
    )
    feature_value = models.CharField(
        max_length=255, unique=True, null=True, blank=True, verbose_name='Значение характеристики'
    )

    def __str__(self):
        if not self.feature:
            return f'Валидатор услуги "{self.service.name}" - характеристика не выбрана'
        return f'Валидатор услуги "{self.service.name}" | ' \
               f'Характеристика - "{self.feature.feature_name}" |' \
               f'Значение - "{self.feature_value}"'


# class CartProduct(models.Model):
#    """"""
#    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
#    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
#    product = models.ForeignKey(Product, verbose_name='Товар', on_delete=models.CASCADE)
#    qty = models.PositiveIntegerField(default=1)
#    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')
#
#    def __str__(self):
#        return "Продукт {} (для корзины)".format(self.product.title)
#
#    def save(self, *args, **kwargs):
#        self.final_price = self.qty * self.product.price
#        super().save(*args, **kwargs)


# class Cart(models.Model):
#    """"""
#    owner = models.ForeignKey('Customer', null=True, verbose_name='Владелец', on_delete=models.CASCADE)
#    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
#    total_products = models.PositiveIntegerField(default=0)
#    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name='Общая цена')
#    in_order = models.BooleanField(default=False)
#    for_anonymous_user = models.BooleanField(default=False)
#
#    def __str__(self):
#        return str(self.id)


class Customer(models.Model):
    """"""
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name='Номер телеофна', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name='Заказы покупателя', related_name='related_customer')

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)


class Order(models.Model):
    """"""
    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ выполнен')
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доставка')
    )

    customer = models.ForeignKey(Customer, verbose_name='Покупатель', related_name='related_orders',
                                 on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    # cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1024, verbose_name='Адрес', null=True, blank=True)
    status = models.CharField(
        max_length=100,
        verbose_name='Статус заказа',
        choices=STATUS_CHOICES,
        default=STATUS_NEW
    )
    buying_type = models.CharField(
        max_length=100,
        verbose_name='Тип заказа',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
    )
    comment = models.TextField(verbose_name='Комментарий к заказу', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')
    order_date = models.DateField(verbose_name='Дата получения заказа', default=timezone.now)

    def __str__(self):
        return str(self.id)


class Review(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    rating = models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

mainapp/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Order
from .models import Review


class OrderForm(forms.ModelForm):
    """"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = 'Дата получения заказа'

    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'buying_type', 'order_date', 'comment'
        )


class LoginForm(forms.ModelForm):
    """"""
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Пользователь с логином {username} не найден в системе.')
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("Неверный пароль")
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password']


class RegistrationForm(forms.ModelForm):

    confirm_password = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)
    phone = forms.CharField(required=False)
    address = forms.CharField(required=False)
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'
        self.fields['confirm_password'].label = 'Подтвердите пароль'
        self.fields['phone'].label = 'Номер телефона'
        self.fields['first_name'].label = 'Ваше имя'
        self.fields['last_name'].label = 'Ваша фамилия'
        self.fields['address'].label = 'Адрес'
        self.fields['email'].label = 'Электронная почта'

    def clean_email(self):
        email = self.cleaned_data['email']
        domain = email.split('.')[-1]
        if domain in ['com', 'net']:
            raise forms.ValidationError(f'Регистрация для домена "{domain}" невозможна')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(f'Данный почтовый адрес уже зарегистрирован в системе')
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Имя {username} занято')
        return username

    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('Пароли не совпадают')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password', 'first_name', 'last_name', 'address', 'phone', 'email']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['name', 'email', 'message', 'rating']

    message = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Введите текст отзыва'}))

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from mainapp.models import Product
from django.contrib import messages
from .cart import Cart
from .forms import CartAddProductForm
from django.http import HttpResponseRedirect
from django.http import HttpResponseRedirect


@require_POST
def cart_add(request, slug):
    if request.user.is_authenticated:
        cart = Cart(request)
        product = get_object_or_404(Product, slug=slug)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product,
                     quantity=cd['quantity'],
                     update_quantity=cd['update'])
    else:
        return redirect('authentication:login')
    return redirect('cart:cart_detail')


def cart_remove(request, slug):
    cart = Cart(request)
    product = Product.objects.get(slug=slug)
    cart.remove(product)
    messages.add_message(request, messages.INFO, "Товар успешно удален")
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

mainapp/templates/mainapp/accessorize_specification.html
<table class="table">
  <tbody>
    <tr>
      <td>Диагональ</td>
      <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
      <td>Тип дисплея</td>
      <td>{{ product.display }}</td>
    </tr>
    <tr>
      <td>Частота процессора</td>
      <td>{{ product.proccesor_freq }}</td>
    </tr>
  </tbody>
</table>

mainapp/templates/mainapp/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
    console.log('Hello!')
</script>
{% endblock %}

mainapp/templates/mainapp/cart.html
{% extends 'base.html' %}

{% block content %}
<h3 class="text-center mt-5 mb-5">Ваша корзина {% if not cart.products.count %} пуста {% endif %}</h3>
{% if messages %}
    {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>{{ message }}</strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
{% endif %}
{% if cart.products.count %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование услуги</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Кол-во</th>
      <th scope="col">Общая цена</th>
      <th scope="col">Действие</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart.products.all %}
        <tr>
          <th scope="row">{{ item.product.title }}</th>
          <td class="w-25"><img src="{{ item.product.image.url }}" class="img-fluid "></td>
          <td>{{ item.product.price }} руб.</td>
          <td>
            <form action="{% url 'change_qty' slug=item.product.slug %}" method="POST">
              {% csrf_token %}
              <input type="number" class="form-control" name="qty" style="width: 70px;" min="1" value="{{ item.qty }}">
              <br>
              <input type="submit" class="btn btn-primary" value="Изменить кол-во">
            </form>
          </td>
          <td>{{ item.final_price }} руб.</td>
          <td>
            <a href="{% url 'delete_from_cart' slug=item.product.slug %}"><button class="btn btn-danger">Удалить из корзины</button></a>
          </td>
        </tr>
    {% endfor %}
        <tr>
          <td colspan="2"></td>
          <td>Итого:</td>
          <td>{{ cart.total_products }}</td>
          <td><strong>{{ cart.final_price }} руб.</strong></td>
          <td><a href="{% url 'checkout' %}"><button class="btn btn-primary">Перейти к оформлению</button></a> </td>
        </tr>
  </tbody>
</table>
{% endif %}
{% endblock content %}

mainapp/templates/mainapp/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class="text-center mt-5 mb-5">Оформление заказа</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование услуги</th>
      <th scope="col">Изображение</th>
      <th scope="col">Цена</th>
      <th scope="col">Кол-во</th>
      <th scope="col">Общая цена</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart.products.all %}
        <tr>
          <th scope="row">{{ item.content_object.title }}</th>
          <td class="w-25"><img src="{{ item.content_object.image.url }}" class="img-fluid "></td>
          <td>{{ item.content_object.price }} руб.</td>
          <td>{{ item.qty }}</td>
          <td>{{ item.final_price }} руб.</td>
        </tr>
    {% endfor %}
        <tr>
          <td colspan="2"></td>
          <td>Итого:</td>
          <td>{{ cart.total_products }}</td>
          <td><strong>{{ cart.final_price }} руб.</strong></td>
        </tr>
  </tbody>
</table>
<hr>
<h3 class="text-center mt-5 mb-5">Форма заказа</h3>
<form action="{% url 'make_order' %}" method="POST">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" class="btn btn-success btn-block mb-3" values="Оформить заказ">
</form>
{% endblock content %}

mainapp/templates/mainapp/login.html
{% extends 'mainapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row" style="margin-bottom: 300px; margin-top: 180px">
    <div class="col-md-6 offset-md-3">
        <h3 class="text-center">Авторизация</h3>
        <hr>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-success" value="Войти">
        </form>
    </div>
</div>

{% endblock content %}

mainapp/templates/mainapp/product_detail.html
{% extends 'mainapp/base.html' %}
{% block content %}
<nav aria-label="breadcrumb" class="mt-3">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'mainapp:base' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="#">{{ product.service.name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ product.title }}</li>
  </ol>
</nav>
<div class="row">
    <div class="col-md-4">
        <img src="{{ product.image.url }}" width="400" height="700" hspace="10" class="img-fluid">
    </div>
    <div class="col-md-8">
        <h3>{{ product.title }}</h3>
        <p>Цена: {{ product.price }}</p>
        <p>Описание: {{ product.description }}</p>
        <form action="{% url 'cart:cart_add' product.slug %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Добавить в корзину">
        </form>
    </div>
</div>

{% endblock%}

mainapp/templates/mainapp/profile.html
{% extends 'base.html' %}

{% block content %}

<h3 class="mt-3 mb-3">Заказы пользователя {{ request.user.username }}</h3>
{% if not orders.count %}
<div class="col-md-12" style="margin-top: 300px; margin-bottom: 300px;">
    <h3>У вас ещё нет заказов.<a href="{% url 'base' %}">Начните делать покупки</a></h3>
</div>
{% else %}
<div class="col-md-12" style="margin-bottom: 250px; margin-top: 250px;">

<table class="table">
    <thead>
        <th scope="col">Номер</th>
        <th scope="col">Статус</th>
        <th scope="col">Сумма</th>
        <th scope="col">Товар</th>
        <th scope="col">Дополнительно</th>
    </thead>
    <tbody>
        {% for order in orders %}
            <tr>
                <th scope="row">{{ order.id }}</th>
                <td scope="row">{{ order.get_status_display }}</td>
                <td scope="row">{{ order.cart.final_price }}</td>
                <td>
                    <ul>
                        {% for item in order.cart.products.all %}

                            <li>{{ item.product.title }} x {{ item.qty }}</li>

                        {% endfor %}
                    </ul>
                </td>
            <td>
                <button class="btn btn-info" data-bs-toggle="modal" data-bs-target="#exampleModal-{{ order.id }}">Дополнительно</button>
                <div class="modal fade" id="exampleModal-{{ order.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog model-lg">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Детализация заказа</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body">
                              <h4 class="text-center">Товар</h4>
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col">Наименование</th>
                                            <th scope="col">Изображение</th>
                                            <th scope="col">Цена</th>
                                            <th scope="col">Кол-во</th>
                                            <th scope="col">Общая цена</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in order.cart.products.all %}
                                            <tr>
                                                <th scope="row">{{ item.product.title }}</th>
                                                <td class="w-25"><img src="{{ item.product.image.url }}" class="img-fluid"></td>
                                                <td><strong>{{ item.product.price }}</strong> руб.</td>
                                                <td>{{ item.qty }}</td>
                                                <td>{{ item.final_price }} руб.</td>
                                            </tr>
                                        {% endfor %}
                                            <tr>
                                                <td colspan="2"></td>
                                                <td>Итого:</td>
                                                <td>{{ order.cart.total_products }}</td>
                                                <td><strong>{{ order.cart.final_price }}</strong> руб.</td>
                                            </tr>
                                    </tbody>
                                </table>
                                    <hr>
                                    <h4 class="text-center">Дополнительная информация</h4>
                                    <p>Имя: <strong>{{ order.first_name }}</strong></p>
                                    <p>Фамилия: <strong>{{ order.last_name }}</strong></p>
                                    <p>Телефон: <strong>{{ order.customer.phone }}</strong></p>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                          </div>
                        </div>
                    </div>
                </div>
            </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endif %}
{% endblock content %}

mainapp/templates/mainapp/ps_specification.html
<table class="table">
  <tbody>
    <tr>
      <td>Диагональ</td>
      <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
      <td>Тип дисплея</td>
      <td>{{ product.display }}</td>
    </tr>
    <tr>
      <td>Частота процессора</td>
      <td>{{ product.proccesor_freq }}</td>
    </tr>
  </tbody>
</table>